schema_version = "2.0.0"
id = "nodebooster"
name = "Node-Booster"
version = "2.0.0"
tagline = "NodeBooster 2.0. Extra Nodes and Functionalities for NodeEditors"
maintainer = "bd3d"
type = "add-on"
tags = ["Geometry Nodes","Node"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://blenderartists.org/t/node-booster-extending-blender-node-editors"
copyright = ["2025 BD3D DIGITAL DESIGN"]